apiVersion: v1
kind: Service
metadata:
  name: student-data-form-nodeport-service
spec:
  type: NodePort
  selector:
    component: student-data-form
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30150

